# Generated by Django 5.0.2 on 2024-03-16 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_room_host_room_name_alter_room_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='host',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
